---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/name: dune-quote-service
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
  name: dune-quote-service
spec:
  ports:
    - name: grpc
      port: 6565
      targetPort: 6565
  selector:
    app.kubernetes.io/name: dune-quote-service
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.dekorate.io/vcs-url: <<unknown>>
  labels:
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
    app.kubernetes.io/name: dune-quote-service
  name: dune-quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.3-SNAPSHOT
      app.kubernetes.io/name: dune-quote-service
  template:
    metadata:
      annotations:
        app.dekorate.io/vcs-url: <<unknown>>
      labels:
        app.kubernetes.io/version: 0.0.3-SNAPSHOT
        app.kubernetes.io/name: dune-quote-service
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: QUOTE_SERVICE
              value: CHUCK
            - name: GRPC_ENABLED
              value: "true"
          image: gamussa/reactive-quote-service:0.0.3-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: dune-quote-service
          ports:
            - containerPort: 6565
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dune-quote-service
  annotations:
    konghq.com/protocols: "grpc,grpcs"
    konghq.com/protocol: "grpc"
spec:
  ingressClassName: kong
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dune-quote-service
                port:
                  number: 6565