---
apiVersion: v1
kind: Service
metadata:
  annotations:
    konghq.com/protocol: grpcs
  labels:
    app.kubernetes.io/name: dune-quote-service
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
  name: dune-quote-service
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 6565
      targetPort: 6565
  selector:
    app.kubernetes.io/name: dune-quote-service
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/version: 0.0.3-SNAPSHOT
    app.kubernetes.io/name: dune-quote-service
  name: dune-quote-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.0.3-SNAPSHOT
      app.kubernetes.io/name: dune-quote-service
  template:
    metadata:
      labels:
        app.kubernetes.io/version: 0.0.3-SNAPSHOT
        app.kubernetes.io/name: dune-quote-service
    spec:
      containers:
        - image: gamussa/reactive-quote-service:0.0.3-SNAPSHOT
          imagePullPolicy: Always
          name: dune-quote-service
          ports:
            - containerPort: 6565
          env:
            - name: GRPC_SERVER_SECURITY_ENABLED
              value: "true"
            - name: GRPC_SERVER_SECURITY_CERTIFICATECHAIN
              value: "file:/mnt/grpc-cert-chain/server.crt"
            - name: GRPC_SERVER_SECURITY_PRIVATEKEY
              value: "file:/mnt/grpc-pk/server.key"
          volumeMounts:
            - mountPath: /mnt/grpc-cert-chain
              name: grpc-cert-chain
            - mountPath: /mnt/grpc-pk
              name: grpc-pk
      volumes:
        - name: grpc-cert-chain
          secret:
            secretName: grpc-cert-chain
        - name: grpc-pk
          secret:
            secretName: grpc-pk
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dune-quote-service
  annotations:
    konghq.com/protocols: "grpc,grpcs"
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: dune-quote-service
                port:
                  number: 6565