apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2021-06-28T17:54:59Z"
  generation: 1
  name: kongplugins.configuration.konghq.com
  resourceVersion: "7069"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/kongplugins.configuration.konghq.com
  uid: 3efdfdef-2f5f-4863-9cd4-50ac2229496c
spec:
  conversion:
    strategy: None
  group: configuration.konghq.com
  names:
    kind: KongPlugin
    listKind: KongPluginList
    plural: kongplugins
    shortNames:
    - kp
    singular: kongplugin
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: Name of the plugin
      jsonPath: .plugin
      name: Plugin-Type
      type: string
    - description: Age
      jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - description: Indicates if the plugin is disabled
      jsonPath: .disabled
      name: Disabled
      priority: 1
      type: boolean
    - description: Configuration of the plugin
      jsonPath: .config
      name: Config
      priority: 1
      type: string
    name: v1
    schema:
      openAPIV3Schema:
        properties:
          config:
            type: object
          configFrom:
            properties:
              secretKeyRef:
                properties:
                  key:
                    type: string
                  name:
                    type: string
                required:
                - name
                - key
                type: object
            type: object
          disabled:
            type: boolean
          plugin:
            type: string
          protocols:
            items:
              enum:
              - http
              - https
              - grpc
              - grpcs
              - tcp
              - tls
              type: string
            type: array
          run_on:
            enum:
            - first
            - second
            - all
            type: string
        required:
        - plugin
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: KongPlugin
    listKind: KongPluginList
    plural: kongplugins
    shortNames:
    - kp
    singular: kongplugin
  conditions:
  - lastTransitionTime: "2021-06-28T17:54:59Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2021-06-28T17:54:59Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  - lastTransitionTime: "2021-06-28T17:54:59Z"
    message: 'spec.versions[0].schema.openAPIV3Schema.type: Required value: must not
      be empty at the root'
    reason: Violations
    status: "True"
    type: NonStructuralSchema
  storedVersions:
  - v1
